### ISSUE TITLE
putUsersNamesUserId not PUTting the names

### ISSUE THREAD

**Issue by disccomp** [kerbeh/valence-wrapper#2]
I'm trying to do this in C# and stumbled across your code and noticed it doesn't appear to actually PUT the JSON string in the request body.

Some context:
https://github.com/kerbeh/valence-wrapper/blob/42f7bd39b1c98633512c1a2aa7504cbed55189e8/src/Service/Users.php#L149-L159
Problem:
https://github.com/kerbeh/valence-wrapper/blob/42f7bd39b1c98633512c1a2aa7504cbed55189e8/src/Service/Users.php#L160-L165

**Comment by kerbeh** [comment]
Thanks for the issue.
Routes other than GET have now been correctly implemented in [7eb6369](https://github.com/kerbeh/valence-wrapper/commit/7eb6369ba78ba6947ad1fb9d6299589c276be335)
